spring:
  application:
    name: collector

logging:
  level:
    root: INFO

collector:
  nuc-max-ram: 15597
  itobey-max-ram: 7772
  odroid-max-ram: 3712
  search-window: 10
  influxdb:
    server: http://influxdb.influxdb:8086
    user: root
    password: ---
    database: datadog_metrics