spring:
  application:
    name: collector

logging:
  level:
    root: INFO

collector:
  nuc-max-ram: 15597
  itobey-max-ram: 7772
  odroid-max-ram: 3712
  search-window: 10
  influxdb:
    url: http://influxdb2.influxdb2:8086
    token: ---
    organization: primary
    bucket: datadog_metrics
