micronaut:
  application:
    name: datadogApi

logging:
  level:
    root: DEBUG

datadog-api-gatherer:
  nuc-max-ram: 15597
  itobey-max-ram: 7772
  odroid-max-ram: 3712
  search-window: 10
  influxdb:
    server: http://192.168.0.34:8086
    user: root
    password: root
    database: datadog_metrics